SECTOR_NAME_EN = {
    "0191": "Agriculture",
    "0192": "Livestock farming",
    "0280": "Forestry, fishing & aquaculture",
    "0580": "Coal & non-metallic mining",
    "0680": "Oil & gas extraction",
    "0791": "Iron ore mining",
    "0792": "Non-ferrous metal ore mining",
    "1091": "Slaughtering, meat, dairy & seafood products",
    "1092": "Sugar manufacturing & refining",
    "1093": "Other food products",
    "1100": "Beverage manufacturing",
    "1200": "Tobacco products",
    "1300": "Textile manufacturing",
    "1400": "Apparel manufacturing",
    "1500": "Footwear & leather products",
    "1600": "Wood products",
    "1700": "Pulp, paper, and paper products",
    "1800": "Printing & recorded-media reproduction",
    "1991": "Petroleum refining & coking",
    "1992": "Biofuel manufacturing",
    "2091": "Chemicals & resins",
    "2092": "Pesticides, paints & other chemicals",
    "2093": "Cleaning products, cosmetics & personal care",
    "2100": "Pharmaceutical products",
    "2200": "Rubber & plastics",
    "2300": "Non-metallic mineral products",
    "2491": "Iron & steel",
    "2492": "Non-ferrous metals & foundries",
    "2500": "Fabricated metal products",
    "2600": "Computer, electronic & optical equipment",
    "2700": "Electrical equipment",
    "2800": "Machinery & mechanical equipment",
    "2991": "Motor vehicles, trucks & buses",
    "2992": "Motor vehicle parts & accessories",
    "3000": "Other transport equipment",
    "3180": "Furniture & miscellaneous manufacturing",
    "3300": "Machinery & equipment repair and installation",
    "3500": "Electricity, gas & utilities",
    "3680": "Water, sewerage & waste management",
    "4180": "Construction",
    "4580": "Wholesale & retail trade",
    "4900": "Land transport",
    "5000": "Water transport",
    "5100": "Air transport",
    "5280": "Warehousing, transport support & postal services",
    "5500": "Accommodation",
    "5600": "Food services",
    "5800": "Publishing & printing",
    "5980": "TV, radio, film & sound activities",
    "6100": "Telecommunications",
    "6280": "Software & information services",
    "6480": "Finance, insurance & pensions",
    "6800": "Real estate activities",
    "6980": "Legal, accounting, consulting & head offices",
    "7380": "Other professional & technical services",
    "7180": "Architecture, engineering, testing & R&D",
    "7700": "Non-real-estate rental & intellectual property",
    "7880": "Administrative & support services",
    "8000": "Security & investigation services",
    "8400": "Public administration, defense & social security",
    "8591": "Public education",
    "8592": "Private education",
    "8691": "Public healthcare",
    "8692": "Private healthcare",
    "9080": "Arts, culture & entertainment",
    "9480": "Associations & other personal services",
    "9700": "Domestic services",
}

def sector_label(
    sector_code: str,
    sector_name_pt: str,
    lang: str = "en",
) -> str:
    if lang == "en":
        return SECTOR_NAME_EN.get(str(sector_code), sector_name_pt)
    return sector_name_pt
